from pysign.parse import parse_hamnosys, ascify

data = [
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], ["", ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], []],
    ["   ", ["meta", "orientation"], []],
    ["   ", ["meta", "contact"], []],
    ["   ", ["meta", "location"], []],
    ["   ", ["meta", "movement"], []],
    ["   ", ["meta", "rest"], "   "],
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], ["", ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], ["", "", ""]],
    ["   ", ["meta", "orientation"], ["", "", ""]],
    ["   ", ["meta", "contact"], []],
    ["   ", ["meta", "location"], ["", "", ""]],
    ["   ", ["meta", "movement"], ["", "", ""]],
    ["   ", ["meta", "rest"], "   "],
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], [["", "", "simultaneous"], ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], ["", "",
        ""]],
    ["   ", ["meta", "orientation"], ["", "",
        ""]],
    ["   ", ["meta", "contact"], []],
    ["   ", ["meta", "location"], ["", "",
        ""]],
    ["   ", ["meta", "movement"], ["", "",
        ""]],
    ["   ", ["meta", "rest"], "   "],
    ["    ", ["symmetry"], []],
    ["    ", ["initial position"], []],
    ["    ", ["dominant", "shape"], ["", ""]],
    ["    ", ["dominant", "orientation"], ["", ""]],
    ["    ", ["dominant", "contact"], ["", ""]],
    ["    ", ["dominant", "location"], ["", ""]],
    ["    ", ["dominant", "movement"], ["", ""]],
    ["    ", ["dominant", "repetition"], [""]],
    ["    ", ["nondominant", "shape"], ["", ""]],
    ["    ", ["nondominant", "orientation"], ["", ""]],
    ["    ", ["nondominant", "location"], ["", ""]],
    ["    ", ["nondominant", "contact"], []],
    ["    ", ["nondominant", "movement"], ["", ""]],
    ["    ", ["meta", "handshape"], []],
    ["    ", ["meta", "orientation"], []],
    ["    ", ["meta", "contact"], ["", "", "", "", "", ""]],
    ["    ", ["meta", "location"], []],
    ["    ", ["meta", "movement"], []],
    ["    ", ["meta", "rest"], "    "],
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], ["", ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], []],
    ["   ", ["meta", "orientation"], []],
    ["   ", ["meta", "contact"], ["", "", "", "", "", ""]],
    ["   ", ["meta", "location"], []],
    ["   ", ["meta", "movement"], []],
    ["   ", ["meta", "rest"], "   "],
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], [["", "", "simultaneous"], ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], []],
    ["   ", ["meta", "orientation"], []],
    ["   ", ["meta", "contact"], []],
    ["   ", ["meta", "location"], []],
    ["   ", ["meta", "movement"], []],
    ["   ", ["meta", "rest"], "   "],
    ["    ", ["symmetry"], [""]],
    ["    ", ["initial position"], [""]],
    ["    ", ["dominant", "shape"], ["", ""]],
    ["    ", ["dominant", "orientation"], ["", ""]],
    ["    ", ["dominant", "contact"], ["", ""]],
    ["    ", ["dominant", "location"], ["", ["", ""]]],
    ["    ", ["dominant", "movement"], ["", [""]]],
    ["    ", ["dominant", "repetition"], [""]],
    ["    ", ["nondominant", "shape"], ["", ""]],
    ["    ", ["nondominant", "orientation"], ["", ""]],
    ["    ", ["nondominant", "location"], ["", ""]],
    ["    ", ["nondominant", "contact"], []],
    ["    ", ["nondominant", "movement"], ["", ""]],
    ["    ", ["meta", "handshape"], []],
    ["    ", ["meta", "orientation"], []],
    ["    ", ["meta", "contact"], ["", "", "", ""]],
    ["    ", ["meta", "location"], ["", "", ""]],
    ["    ", ["meta", "movement"], []],
    ["    ", ["meta", "rest"], "    "],
    ["    ", ["symmetry"], [""]],
    ["    ", ["initial position"], []],
    ["    ", ["dominant", "shape"], ["", ""]],
    ["    ", ["dominant", "orientation"], ["", ""]],
    ["    ", ["dominant", "contact"], ["", ""]],
    ["    ", ["dominant", "location"], ["", ""]],
    ["    ", ["dominant", "movement"], [["", "", "simultaneous"], ""]],
    ["    ", ["dominant", "repetition"], [""]],
    ["    ", ["nondominant", "shape"], ["", ""]],
    ["    ", ["nondominant", "orientation"], ["", ""]],
    ["    ", ["nondominant", "location"], ["", ""]],
    ["    ", ["nondominant", "contact"], []],
    ["    ", ["nondominant", "movement"], ["", ""]],
    ["    ", ["meta", "handshape"], []],
    ["    ", ["meta", "orientation"], []],
    ["    ", ["meta", "contact"], ["", "", "", ""]],
    ["    ", ["meta", "location"], ["", "", ""]],
    ["    ", ["meta", "movement"], []],
    ["    ", ["meta", "rest"], "    "],
    ["    ", ["symmetry"], [""]],
    ["    ", ["initial position"], [""]],
    ["    ", ["dominant", "shape"], ["", ""]],
    ["    ", ["dominant", "orientation"], ["", ""]],
    ["    ", ["dominant", "contact"], ["", ""]],
    ["    ", ["dominant", "location"], ["", ""]],
    ["    ", ["dominant", "movement"], [["", "", "simultaneous"], ""]],
    ["    ", ["dominant", "repetition"], [""]],
    ["    ", ["nondominant", "shape"], ["", ""]],
    ["    ", ["nondominant", "orientation"], ["", ""]],
    ["    ", ["nondominant", "location"], ["", ""]],
    ["    ", ["nondominant", "contact"], []],
    ["    ", ["nondominant", "movement"], ["", ""]],
    ["    ", ["meta", "handshape"], []],
    ["    ", ["meta", "orientation"], []],
    ["    ", ["meta", "contact"], []],
    ["    ", ["meta", "location"], ["", "", ""]],
    ["    ", ["meta", "movement"], []],
    ["    ", ["meta", "rest"], "    "],
    ["   ", ["symmetry"], []],
    ["   ", ["initial position"], []],
    ["   ", ["dominant", "shape"], ["", ""]],
    ["   ", ["dominant", "orientation"], ["", ""]],
    ["   ", ["dominant", "contact"], ["", ""]],
    ["   ", ["dominant", "location"], ["", ""]],
    ["   ", ["dominant", "movement"], [["", "", ""], ""]],
    ["   ", ["dominant", "repetition"], [""]],
    ["   ", ["nondominant", "shape"], ["", ""]],
    ["   ", ["nondominant", "orientation"], ["", ""]],
    ["   ", ["nondominant", "location"], ["", ""]],
    ["   ", ["nondominant", "contact"], []],
    ["   ", ["nondominant", "movement"], ["", ""]],
    ["   ", ["meta", "handshape"], []],
    ["   ", ["meta", "orientation"], []],
    ["   ", ["meta", "contact"], ["", ""]],
    ["   ", ["meta", "location"], []],
    ["   ", ["meta", "movement"], []],
    ["   ", ["meta", "rest"], "   "],
        ]

def test_parse_hamnosys():
    for a, b, c in data:
        out = parse_hamnosys(a)
        if len(b) == 1:
            assert out[b[0]] == c
        if len(b) == 2:
            assert out[b[0]][b[1]] == c

if __name__ == '__main__':
    from tabulate import tabulate
    table = []
    for a, b, c in data:
        out = parse_hamnosys(a)
        if len(b) == 1:
            if out[b[0]] != c:
                table += [[a, b[0], "", out[b[0]], c]]
        if len(b) == 2:
            if out[b[0]][b[1]] != c:
                table += [[a, b[0], b[1], out[b[0]][b[1]], c]]
    print(tabulate(table, headers=['input', 'par1', 'par2', 'out',
        'expected'], tablefmt='pipe'))

#strings = ["   ", "   ", 
#        "   ", "    ",
#        "    ",
#        ]
#
#for string in strings:
#    data = parse_hamnosys(string, ascify_text=False)
#    table = [
#            [
#            'handshape', 
#            'dominant', 
#            'shape', 
#            data['handshape']['dominant']['shape'],
#            ascify(data['handshape']['dominant']['shape'])],
#            [
#            'handshape', 
#            'dominant', 
#            'change', 
#            data['handshape']['dominant']['change'],
#            ascify(data['handshape']['dominant']['change'])],
#            [
#            'handshape', 
#            'nonnondominant', 
#            'shape', 
#            data['handshape']['nondominant']['shape'],
#            ascify(data['handshape']['nondominant']['shape'])],
#            [
#            'handshape', 
#            'nondominant', 
#            'change', 
#            data['handshape']['nondominant']['change'],
#            ascify(data['handshape']['nondominant']['change'])],
#            ['errors', '', '', data['errors'][:2], ''],
#            ['rest', '', '', data['rest'], ascify(data['rest'])[:30]]
#            ]
#    print(tabulate(table, tablefmt='pipe'))
#    input()
